global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.0.87:8082']