version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitor-net

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - monitor-net

  kafka-1:
    image: douglasrocha06/kafka-metrics:latest
    container_name: kafka-1
    depends_on:
      - zookeeper-1
    ports:
      - "8081:8081"
    environment:
      EXTRA_ARGS: "-javaagent:/etc/kafka/jmx_prometheus_javaagent-0.16.1.jar=8081:/etc/kafka/kafka-2_0_0.yml"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9091
    networks:
      - monitor-net

  kafka-2:
    image: douglasrocha06/kafka-metrics:latest
    container_name: kafka-2
    depends_on:
      - zookeeper-1
    ports:
      - "8082:8082"
    environment:
      EXTRA_ARGS: "-javaagent:/etc/kafka/jmx_prometheus_javaagent-0.16.1.jar=8082:/etc/kafka/kafka-2_0_0.yml"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
    networks:
      - monitor-net

  kafka-3:
    image: douglasrocha06/kafka-metrics:latest
    container_name: kafka-3
    depends_on:
      - zookeeper-1
    ports:
      - "8083:8083"
    environment:
      EXTRA_ARGS: "-javaagent:/etc/kafka/jmx_prometheus_javaagent-0.16.1.jar=8083:/etc/kafka/kafka-2_0_0.yml"
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9093
    networks:
      - monitor-net


  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-1:9091,kafka-2:9092,kafka-3:9093"
    networks:
      - monitor-net
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3